[package]
name = "pcg"
version = "0.3.0" # reflects current chapter
authors = ["James Tranovich <jtranovich@gmail.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"

[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"

[dependencies.pistoncore-event]
git = "https://github.com/pistondevelopers/event"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"

[dependencies.piston2d-opengl_graphics]
git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"

[dependencies.pistoncore-input]
git = "https://github.com/pistondevelopers/input"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.pistoncore-window]
git = "https://github.com/pistondevelopers/window"

[dependencies.piston-viewport]
git = "https://github.com/pistondevelopers/viewport"

[dependencies.freetype-rs]
git = "https://github.com/pistondevelopers/freetype-rs"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"

[dependencies.rand]
rand = "0.1.2"

[dependencies.threadpool]
threadpool = "0.1.0"

[dependencies.num_cpus]
num_cpus = "*"

[profile.dev]
debug = false
