[package]
name = "pcg"
version = "0.3.0" # reflects current chapter
authors = ["James Tranovich <jtranovich@gmail.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"
piston = "0.10.1"
piston2d-opengl_graphics = "0.12.0"
piston2d-graphics = "0.9.0"
pistoncore-sdl2_window = "0.13.0"
freetype-rs = "0.3.0"

[dependencies.pistoncore-event]
git = "https://github.com/pistondevelopers/event"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"

[dependencies.pistoncore-input]
git = "https://github.com/pistondevelopers/input"

[dependencies.pistoncore-window]
git = "https://github.com/pistondevelopers/window"

[dependencies.piston-viewport]
git = "https://github.com/pistondevelopers/viewport"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs"

[dependencies.rand]
rand = "0.1.2"

[dependencies.threadpool]
threadpool = "0.1.0"

[dependencies.num_cpus]
num_cpus = "*"

[profile.dev]
debug = false
