[main]
window_width = 400
window_height = 416
tiles_width = 25
tiles_height = 25
tile_width = 16
tile_height = 16
spritesheet = "dawnlike"
threads = 50
font = "./assets/Inconsolata.otf"
font_size = 14
fps = 10
animation_speed = 10 # once per X frames

[spritesheets.dungeon]
path = "./assets/16x16_Jerom_CC-BY-SA-3.0_0.png"
occupant_chance = 0.05 # purely for cosmetic flavor

[spritesheets.dungeon.cells]
tiles = ["floor", "wall", "entrance", "exit", "door"]
occupants = ["monster", "treasure", "trap", "teleporter"]
items = []

[spritesheets.dawnlike]
path = "./assets/dawnlike-pcg.png"
occupant_chance = 0.05 # purely for cosmetic flavor

[spritesheets.dawnlike.cells]
tiles = ["floor", "wall", "entrance", "exit", "door"]
occupants = ["monster", "treasure", "trap", "teleporter"]
items = []

[mu-lambda]
iterations = 5
mu = 2
lambda = 8
mutation = 0.33 # percentage points
#strategy = "RandomSeed"
#strategy = "ListOfWalls"
#strategy = "WallPatterns"
strategy = "DesirableProperties"
evaluations = ["check_1x1_rooms", "has_entrance_exit", "doors_are_useful", "rooms_are_accessible", ]
evaluation_weights = [5.0, 20.0, 3.0, 10.0]

[list-of-walls]
door_chance = 0.25 # percentage points
coverage = 0.50 # percentage points

[wallpatterns.tiles]
floor = "_"
wall = "X"
entrance = ">"
exit = "<"
door = "d"
width = 5
height = 5

[wallpatterns.rooms]
empty = ["_____",
         "_____",
         "_____",
         "_____",
         "_____"]
altar = ["_____",
         "__X__",
         "_X X_",
         "__X__",
         "_____"]
down_ = ["___X_",
         "__X__",
         "_X_XX",
         "___>d",
         "XX_XX"]
up___ = ["____X",
         "____X",
         "__>__",
         "X____",
         "X____"]
rand1 = ["_X___",
         "_X__X",
         "_X_X_",
         "__X__",
         "_____"]
rand2 = ["____X",
         "_X_ X",
         "_X  X",
         "_XXdX",
         "_____"]
rand3 = ["__X__",
         "_X___",
         "X___X",
         "___d_",
         "__XX_"]
rand4 = ["__X__",
         "__XdX",
         "XXX__",
         "__XX_",
         "___X_"]
rand5 = ["X____",
         "X___X",
         "X____",
         "___X_",
         "___X_"]
rand6 = ["XXXX_",
         "X__X_",
         "X__X_",
         "XdXX_",
         "_____"]
rand7 = ["_X___",
         "__X__",
         "__X__",
         "___X_",
         "XX___"]

[desirable_patterns]
room_number = 20
room_size = 7
doors = 5
monsters = 20
branching = 0.05
