[sprites]
tile_width = 16
tile_height = 16

    [sprites.tiles]
    floor = [5, 2]
    wall = [2, 1]
    entrance = [3, 1]
    exit = [4, 1]
    door = [1, 0]

    [sprites.occupants]
    monster = [0, 22]
    treasure = [4, 8]
    trap = [8, 1]
    teleporter = [4, 6]

    [sprites.icons]
    death = [3, 24]
    sleep = [4, 24]

    [sprites.health]
    5 = [0, 27]
    4 = [1, 27]
    3 = [2, 27]
    2 = [3, 27]
    1 = [4, 27]

    [sprites.meter]
    tile_width = 8
    tile_height = 8
    1 = [1, 54]
    2 = [2, 54]
    3 = [3, 54]
    4 = [4, 54]
