[sprites]
tile_width = 16
tile_height = 16

    [sprites.tiles]
    floor = [2, 5]
    wall = [1, 2]
    entrance = [1, 3]
    exit = [1, 4]
    door = [0, 1]

    [sprites.occupants]
    monster = [22,0]
    treasure = [8, 4]
    trap = [1, 8]
    teleporter = [6, 4]

    [sprites.icons]
    death = [26, 3]
    sleep = [26, 4]

    [sprites.health]
    5 = [27, 0]
    4 = [27, 1]
    3 = [27, 2]
    2 = [27, 3]
    1 = [27, 4]

    [sprites.meter]
    tile_width = 8
    tile_height = 8
    1 = [54, 1]
    2 = [54, 2]
    3 = [54, 3]
    4 = [54, 4]
