# dawnlike, 16x16 universal rogue-like tileset v1.8, created by DawnBringer
# CC-BY-SA 3.0 license
[sprites]
tile_width = 16
tile_height = 16
wall = [0, 0]
exit = [1, 0]
entrance = [2, 0]
floor = [3, 0]
trap = [4, 0]
teleporter = [5, 0]
monster = [6, 0]
door = [0, 1]
treasure = [1, 1]
