[main]
window_width = 400
window_height = 416
tiles_width = 25
tiles_height = 25
spritesheet = "dungeon"
threads = 50

[spritesheets.dungeon]
path = "./assets/16x16_Jerom_CC-BY-SA-3.0_0.png"

[spritesheets.dungeon.cells]
tiles = ["floor", "wall", "entrance", "exit", "door"]
occupants = ["monster", "treasure", "trap", "teleporter"]
items = []

[mu-lambda]
iterations = 2
mu = 20
lambda = 80
#strategy = "RandomSeed"
strategy = "ListOfWalls"
evaluations = ["check_1x1_rooms", ]
