[main]
window_width = 400
window_height = 416
tiles_width = 25
tiles_height = 25
tile_width = 16
tile_height = 16
spritesheet = "dungeon"
threads = 50
font = "./assets/Inconsolata.otf"
font_size = 14

[spritesheets.dungeon]
path = "./assets/16x16_Jerom_CC-BY-SA-3.0_0.png"

[spritesheets.dungeon.cells]
tiles = ["floor", "wall", "entrance", "exit", "door"]
occupants = ["monster", "treasure", "trap", "teleporter"]
items = []

[mu-lambda]
iterations = 2
mu = 2
lambda = 8
mutation = 0.33 # percentage points
#strategy = "RandomSeed"
strategy = "ListOfWalls"
#strategy = "WallPatterns"
evaluations = ["check_1x1_rooms", "has_entrance_exit", "doors_are_useful", "rooms_are_accessible", ]
evaluation_weights = [5.0, 4.0, 3.0, 10.0]

[list-of-walls]
door_chance = 0.25 # percentage points
coverage = 0.50 # percentage points

[wallpatterns.tiles]
floor = "_"
wall = "X"
entrance = ">"
exit = "<"
door = "d"
width = 5
height = 5

[wallpatterns.rooms]
empty = ["_____",
         "_____",
         "_____",
         "_____",
         "_____"]
altar = ["_____",
         "__X__",
         "_X X_",
         "__X__",
         "_____"]
down_ = ["___X_",
         "__X__",
         "_X_XX",
         "___>d",
         "XX_XX"]
up___ = ["____X",
         "____X",
         "__>__",
         "X____",
         "X____"]
rand1 = ["_X___",
         "_X__X",
         "_X_X_",
         "__X__",
         "_____"]
rand2 = ["____X",
         "_X_ X",
         "_X  X",
         "_XXdX",
         "_____"]
rand3 = ["__X__",
         "_X___",
         "X___X",
         "___d_",
         "__XX_"]
rand4 = ["__X__",
         "__XdX",
         "XXX__",
         "__XX_",
         "___X_"]
