[main]
window_width = 400
window_height = 400
spritesheet = "dungeon"

[spritesheets.dungeon]
path = "./assets/16x16_Jerom_CC-BY-SA-3.0_0.png"

[spritesheets.dungeon.cells]
tiles = ["floor", "wall", "entrance", "exit", "door"]
occupants = ["monster", "treasure", "trap", "teleporter"]
items = []
